#!/bin/bash

MERGE_REQUEST_ID="$1"
BRANCH_NAME="$2"

function usage() {
    cat <<EOF
Usage:
  git fetch-merge-request [merge request id] [destination branch]

ex:
  git fetch-merge-request 1024 merge-request-branch
EOF
}

if [ "$MERGE_REQUEST_ID" == "" -o "$BRANCH_NAME" == "" ]; then
    usage
    exit 1
elif [ "$MERGE_REQUEST_ID" == "-h" -o "$MERGE_REQUEST_ID" == "--help" ]; then
    usage
    exit 0
fi

git fetch origin "merge-requests/${MERGE_REQUEST_ID}/head:${BRANCH_NAME}"
