#!/bin/bash

PULL_REQUEST_ID="$1"
BRANCH_NAME="$2"

function usage() {
    cat <<EOF
Usage:
  git fetch-pull-request [pull request id] [destination branch]

ex:
  git fetch-pull-request 1024 pull-request-branch
EOF
}

if [ "$PULL_REQUEST_ID" == "" -o "$PULL_NAME" == "" ]; then
    usage
    exit 1
elif [ "$PULL_REQUEST_ID" == "-h" -o "$PULL_REQUEST_ID" == "--help" ]; then
    usage
    exit 0
fi

git fetch origin "pull/${MERGE_REQUEST_ID}/head:${BRANCH_NAME}"
