#!/bin/bash

PULL_REQUEST_ID="$1"

set -e

function usage() {
    cat <<EOF
Usage:
  git pr-squash [merge request id]

ex:
  git pr-squash 1024
EOF
}

if [ "$PULL_REQUEST_ID" == "" ]; then
    usage
    exit 1
elif [ "$PULL_REQUEST_ID" == "-h" -o "$PULL_REQUEST_ID" == "--help" ]; then
    usage
    exit 0
fi

BRANCH_NAME="pr-${PULL_REQUEST_ID}"

git fetch origin "pull/${PULL_REQUEST_ID}/head:${BRANCH_NAME}"
author=$(git --no-pager show -s --format='%an <%ae>' "${BRANCH_NAME}")
git merge --squash "${BRANCH_NAME}"
git commit
git commit -C HEAD --amend --author "$author"
git branch -D "${BRANCH_NAME}"
