export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export ZSH="$HOME/.oh-my-zsh"

# Locale settings
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Asdf settings
source $HOME/.asdf/asdf.sh

# fzf auto complete
export FZF_BASE="$HOME/.fzf"

# git scripts
export PATH="$PATH:$HOME/.git"

# go
export GOPATH=$HOME/.go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

plugins=(fzf)

source $ZSH/oh-my-zsh.sh

autoload -U colors; colors

# load antibody plugins
source <(antibody init)
source $HOME/.zsh/plugins

typeset -U config_files
config_files=($HOME/.zsh/*.zsh)

# load the path files
for file in ${config_files[@]}; do
  source "$file"
done

RPROMPT='%{$fg[blue]%}($ZSH_KUBECTL_PROMPT)%{$reset_color%}'

docker() {
 if [[ `uname -m` == "arm64" ]] && [[ "$1" == "run" || "$1" == "build" ]]; then
    /usr/local/bin/docker "$1" --platform linux/amd64 "${@:2}"
  else
     /usr/local/bin/docker "$@"
  fi
}

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && \. "/usr/local/opt/nvm/etc/bash_completion"

# RVM
export PATH="$PATH:$HOME/.rvm/bin"
